//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServico")]
public interface IServico
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Mensagem", ReplyAction="http://tempuri.org/IServico/MensagemResponse")]
    string Mensagem(string nome);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Mensagem", ReplyAction="http://tempuri.org/IServico/MensagemResponse")]
    System.Threading.Tasks.Task<string> MensagemAsync(string nome);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServicoChannel : IServico, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServicoClient : System.ServiceModel.ClientBase<IServico>, IServico
{
    
    public ServicoClient()
    {
    }
    
    public ServicoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Mensagem(string nome)
    {
        return base.Channel.Mensagem(nome);
    }
    
    public System.Threading.Tasks.Task<string> MensagemAsync(string nome)
    {
        return base.Channel.MensagemAsync(nome);
    }
}
